environment:
  matrix:
    - nodejs_version: '16'
    - nodejs_version: '15'
    - nodejs_version: '14'
    - nodejs_version: '13'
    - nodejs_version: '12'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: 'off'
